name: Deploy to Vercel

on:
  push:
    branches:
      - main  # O branch que você quer monitorar para deploy

jobs:
  deploy-client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies for client
        run: |
          cd client
          npm install

      - name: Build client
        run: |
          cd client
          npm run build

      - name: Deploy client to Vercel
        run: |
          cd client
          npm install -g vercel
          vercel --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

  deploy-server:
    runs-on: ubuntu-latest
    # needs: deploy-client  # Aguarda o job de deploy do client terminar

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies for server
        run: |
          cd server
          npm install

      - name: Build server
        run: |
          cd server
          npm run build

      - name: Deploy server to Vercel
        run: |
          cd server
          npm install -g vercel
          vercel --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
